#!/usr/bin/env python3
"""Parse @manager markdown specs into GitHub-ready JSON with metadata.

This script parses markdown specifications generated by the @manager agent
and outputs JSON with all necessary GitHub metadata (labels, project fields).
"""

import json
import os
import re
import sys
from typing import Dict, List, Optional


# GitHub metadata (synced with .opencode/config/manager/github-metadata.yaml)
GITHUB_METADATA = {
    "project_id": "PVT_kwHOAeQxRM4BQVim",
    "field_ids": {
        "status": "PVTSSF_lAHOAeQxRM4BQVimzg-fIIo",
        "priority": "PVTSSF_lAHOAeQxRM4BQVimzg-fsa4",
        "story_points": "PVTF_lAHOAeQxRM4BQVimzg-fxsg",
        "issue_type": "PVTSSF_lAHOAeQxRM4BQVimzg-gKWI"
    },
    "field_values": {
        "status": {
            "todo": "f75ad846",
            "in_progress": "47fc9ee4",
            "done": "98236657"
        },
        "priority": {
            "must_have": "a76e54fc",
            "should_have": "0aafcd8f",
            "could_have": "c6de7461",
            "wont_have": "808b8ca6"
        },
        "issue_type": {
            "bug": "251c6465",
            "story": "d2a6d334",
            "epic": "d895a262",
            "task": "1bc4fa51",
            "item": "6f19c456"
        }
    }
}


def parse_frontmatter(content: str) -> Dict[str, str]:
    """Extract YAML frontmatter from markdown content."""
    if not content.startswith('---'):
        return {}
    
    lines = content.split('\n')
    end_idx = None
    for i, line in enumerate(lines[1:], 1):
        if line.strip() == '---':
            end_idx = i
            break
    
    if end_idx is None:
        return {}
    
    fm_content = '\n'.join(lines[1:end_idx])
    result = {}
    
    for line in fm_content.split('\n'):
        line = line.strip()
        if ':' in line:
            key, value = line.split(':', 1)
            result[key.strip()] = value.strip()
    
    return result


def extract_body(content: str) -> str:
    """Extract body content (excluding frontmatter)."""
    if not content.startswith('---'):
        return content
    
    lines = content.split('\n')
    end_idx = None
    for i, line in enumerate(lines[1:], 1):
        if line.strip() == '---':
            end_idx = i
            break
    
    if end_idx is None:
        return content
    
    return '\n'.join(lines[end_idx + 1:]).strip()


def extract_github_metadata(content: str) -> Optional[Dict]:
    """Extract GitHub metadata comment block from markdown."""
    pattern = r'<!-- GITHUB_METADATA\n(.*?)\n-->'
    match = re.search(pattern, content, re.DOTALL)
    
    if not match:
        return None
    
    try:
        return json.loads(match.group(1))
    except json.JSONDecodeError:
        return None


def normalize_priority(priority: str) -> str:
    """Normalize priority value to label format."""
    mapping = {
        "must have": "must-have",
        "should have": "should-have",
        "could have": "could-have",
        "won't have": "won't-have",
        "must-have": "must-have",
        "should-have": "should-have",
        "could-have": "could-have",
        "won't-have": "won't-have"
    }
    return mapping.get(priority.lower(), priority)


def normalize_issue_type(issue_type: str) -> str:
    """Normalize issue type value."""
    return issue_type.lower()


def get_priority_field_value(priority: str) -> Optional[str]:
    """Get GitHub project field value ID for priority."""
    mapping = {
        "must-have": "must_have",
        "should-have": "should_have",
        "could-have": "could_have",
        "won't-have": "wont_have"
    }
    key = mapping.get(priority.lower())
    if key:
        return GITHUB_METADATA["field_values"]["priority"].get(key)
    return None


def get_issue_type_field_value(issue_type: str) -> Optional[str]:
    """Get GitHub project field value ID for issue type."""
    return GITHUB_METADATA["field_values"]["issue_type"].get(issue_type.lower())


def build_labels(frontmatter: Dict) -> List[str]:
    """Build list of GitHub labels from frontmatter."""
    labels = ["status:backlog"]  # Always include initial status
    
    # Add issue type label
    issue_type = frontmatter.get('issue_type', '')
    if issue_type:
        labels.append(f"issue:{normalize_issue_type(issue_type)}")
    
    # Add priority label
    priority = frontmatter.get('priority', '')
    if priority and priority != 'null':
        labels.append(f"priority:{normalize_priority(priority)}")
    
    # Add estimate label
    estimate = frontmatter.get('estimate', '')
    if estimate and estimate != 'null':
        labels.append(f"estimate:{estimate}")
    
    # Add scope label
    scope = frontmatter.get('scope', '')
    if scope and scope != 'null':
        labels.append(f"scope:{scope}")
    
    # Add blocked label
    blocked_by = frontmatter.get('blocked_by', '')
    if blocked_by and blocked_by != 'null':
        labels.append("blocked")
    
    # Add has-parent label
    parent_link = frontmatter.get('parent_link', '')
    if parent_link and parent_link != 'null':
        labels.append("has-parent")
    
    return labels


def build_project_fields(frontmatter: Dict) -> Dict[str, str]:
    """Build GitHub project field updates."""
    fields = {}
    
    # Status (always Todo initially)
    fields[GITHUB_METADATA["field_ids"]["status"]] = GITHUB_METADATA["field_values"]["status"]["todo"]
    
    # Priority
    priority = frontmatter.get('priority', '')
    if priority and priority != 'null':
        priority_id = get_priority_field_value(priority)
        if priority_id:
            fields[GITHUB_METADATA["field_ids"]["priority"]] = priority_id
    
    # Issue type
    issue_type = frontmatter.get('issue_type', '')
    if issue_type:
        type_id = get_issue_type_field_value(issue_type)
        if type_id:
            fields[GITHUB_METADATA["field_ids"]["issue_type"]] = type_id
    
    # Story points
    estimate = frontmatter.get('estimate', '')
    if estimate and estimate != 'null' and estimate.isdigit():
        fields[GITHUB_METADATA["field_ids"]["story_points"]] = estimate
    
    return fields


def parse_spec(file_path: str) -> Dict:
    """Parse a @manager markdown spec into GitHub-ready JSON.
    
    Returns:
        Dictionary with keys:
            - title: Issue title
            - body: Issue body (markdown)
            - labels: List of label strings
            - project_id: GitHub project ID
            - project_fields: Dict of field_id -> value_id
            - blocked_by: Issue number (if present)
            - parent_link: Issue number (if present)
    """
    with open(file_path, 'r') as f:
        content = f.read()
    
    frontmatter = parse_frontmatter(content)
    body = extract_body(content)
    
    # Remove GitHub metadata comment from body
    body = re.sub(r'<!-- GITHUB_METADATA\n.*?\n-->\n*', '', body, flags=re.DOTALL)
    
    # Build output
    result = {
        "title": frontmatter.get('title', ''),
        "body": body.strip(),
        "labels": build_labels(frontmatter),
        "project_id": GITHUB_METADATA["project_id"],
        "project_fields": build_project_fields(frontmatter)
    }
    
    # Add optional fields
    blocked_by = frontmatter.get('blocked_by', '')
    if blocked_by and blocked_by != 'null':
        result["blocked_by"] = blocked_by
    
    parent_link = frontmatter.get('parent_link', '')
    if parent_link and parent_link != 'null':
        result["parent_link"] = parent_link
    
    return result


def main():
    """CLI entry point."""
    if len(sys.argv) < 2:
        print("Usage: parse_spec.py <spec_file.md> [--output <file.json>]", file=sys.stderr)
        sys.exit(1)
    
    spec_file = sys.argv[1]
    
    if not os.path.exists(spec_file):
        print(f"Error: File not found: {spec_file}", file=sys.stderr)
        sys.exit(1)
    
    try:
        result = parse_spec(spec_file)
        
        # Determine output
        if '--output' in sys.argv:
            idx = sys.argv.index('--output')
            if idx + 1 < len(sys.argv):
                output_file = sys.argv[idx + 1]
                with open(output_file, 'w') as f:
                    json.dump(result, f, indent=2)
                print(f"✅ Parsed spec written to: {output_file}")
            else:
                print("Error: --output requires a filename", file=sys.stderr)
                sys.exit(1)
        else:
            print(json.dumps(result, indent=2))
    
    except Exception as e:
        print(f"Error parsing spec: {e}", file=sys.stderr)
        sys.exit(1)


if __name__ == '__main__':
    main()
